(() => {
const KEY='daily-streaks-tasks-v1'; const $=s=>document.querySelector(s); let tasks=load(), editing=null, addingTo=null, draggingId=null, movingId=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(tasks));window.DailySync?.queue()}
function id(){return crypto.randomUUID()}
function find(nodes,target,parent=null){for(const node of nodes){if(node.id===target)return{node,parent,nodes};const hit=find(node.children||[],target,node);if(hit)return hit}return null}
function descendants(node,value){node.done=value;(node.children||[]).forEach(child=>descendants(child,value))}
function syncParents(){function visit(node){const kids=node.children||[];kids.forEach(visit);if(kids.length)node.done=kids.every(k=>k.done)}tasks.forEach(visit)}
function openCount(nodes=tasks){return nodes.reduce((n,t)=>n+(t.done?0:1)+openCount(t.children||[]),0)}
function count(nodes){return nodes.reduce((n,t)=>n+1+count(t.children||[]),0)}
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function renderNode(t){const kids=t.children||[], childLabel=kids.length?`<span class="child-count">${count(kids)} subtask${count(kids)===1?'':'s'}</span>`:'';return `<div class="task-node" data-id="${t.id}" draggable="true"><div class="task-row ${t.done?'done':''}"><button class="check ${t.done?'done':''}" data-action="toggle" aria-label="Toggle ${esc(t.title)}"></button><span class="task-name">${esc(t.title)}</span>${childLabel}<div class="row-actions"><button class="action" data-action="add">+ Subtask</button><button class="action" data-action="move">Move</button><button class="action" data-action="edit">Edit</button><button class="action delete" data-action="delete">×</button></div></div>${kids.length?`<div class="children">${kids.map(renderNode).join('')}</div>`:''}</div>`}
function render(){syncParents();save();const open=tasks.filter(t=>!t.done), done=tasks.filter(t=>t.done);$('#open-summary').textContent=openCount()?`${openCount()} open task${openCount()===1?'':'s'}`:'Everything is complete.';$('#task-list').innerHTML=open.map(renderNode).join('');$('#empty-state').hidden=tasks.length>0;$('#completed-section').hidden=!done.length;$('#completed-count').textContent=done.length?`(${done.length})`:'';$('#completed-list').innerHTML=done.map(renderNode).join('')}
function openDialog({task=null,parent=null}={}){editing=task?.id||null;addingTo=parent?.id||null;const f=$('#task-form');f.reset();$('#dialog-kicker').textContent=task?'EDIT TASK':parent?'NEW SUBTASK':'NEW TASK';$('#dialog-title').textContent=task?'Rename this task':parent?`Break down “${parent.title}”`:'What needs doing?';$('#save-task').textContent=task?'Save changes':'Add task';if(task)f.title.value=task.title;$('#task-dialog').showModal();f.title.focus()}
function flatten(nodes, depth=0, items=[]){nodes.forEach(node=>{items.push({node,depth});flatten(node.children||[],depth+1,items)});return items}
function openMove(task){movingId=task.id;$('#move-title').textContent=`Move “${task.title}”`;const options=flatten(tasks).filter(item=>!contains(task,item.node.id)).map(item=>`<option value="${item.node.id}">${'— '.repeat(item.depth)}${esc(item.node.title)}</option>`).join('');$('#move-target').innerHTML=`<option value="root">Top level</option>${options}`;$('#move-dialog').showModal()}
function close(){document.querySelectorAll('dialog[open]').forEach(d=>d.close())}
$('#add-root').onclick=()=>openDialog();$('#add-empty').onclick=()=>openDialog();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);
document.body.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const hit=find(tasks,button.closest('.task-node').dataset.id);if(!hit)return;const action=button.dataset.action;if(action==='toggle'){descendants(hit.node,!hit.node.done);syncParents();save();render()}if(action==='add')openDialog({parent:hit.node});if(action==='move')openMove(hit.node);if(action==='edit')openDialog({task:hit.node});if(action==='delete'&&confirm(`Delete “${hit.node.title}” and all of its subtasks?`)){hit.nodes.splice(hit.nodes.indexOf(hit.node),1);syncParents();save();render()}});
$('#task-form').onsubmit=e=>{e.preventDefault();const title=e.currentTarget.title.value.trim();if(!title)return;if(editing)find(tasks,editing).node.title=title;else {const newTask={id:id(),title,done:false,children:[]};if(addingTo){const parent=find(tasks,addingTo).node;parent.children.push(newTask);parent.done=false}else tasks.unshift(newTask)}save();close();render()};
$('#move-form').onsubmit=e=>{e.preventDefault();const sourceHit=find(tasks,movingId);const targetId=$('#move-target').value;if(!sourceHit)return;const source=sourceHit.node;const target=targetId==='root'?null:find(tasks,targetId)?.node;sourceHit.nodes.splice(sourceHit.nodes.indexOf(source),1);if(target){target.children=target.children||[];target.children.push(source);target.done=false}else tasks.unshift(source);syncParents();save();close();render()};
$('#toggle-completed').onclick=()=>{$('#completed-list').hidden=!$('#completed-list').hidden};render();
window.addEventListener('daily-sync-pulled',()=>{tasks=load();render()});
function contains(node, targetId){return node.id===targetId||(node.children||[]).some(child=>contains(child,targetId))}
function clearDropTargets(){document.querySelectorAll('.drop-target,.root-drop').forEach(el=>el.classList.remove('drop-target','root-drop'))}
document.body.addEventListener('dragstart',e=>{const card=e.target.closest('.task-node');if(!card)return;draggingId=card.dataset.id;card.classList.add('is-dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',draggingId)});
document.body.addEventListener('dragend',e=>{draggingId=null;document.querySelectorAll('.is-dragging').forEach(el=>el.classList.remove('is-dragging'));clearDropTargets()});
document.body.addEventListener('dragover',e=>{if(!draggingId)return;const target=e.target.closest('.task-node');const source=find(tasks,draggingId)?.node;if(target&&source&&!contains(source,target.dataset.id)&&target.dataset.id!==draggingId){e.preventDefault();clearDropTargets();target.classList.add('drop-target');return}const root=e.target.closest('#task-list');if(root){e.preventDefault();clearDropTargets();root.classList.add('root-drop')}});
document.body.addEventListener('dragleave',e=>{if(!e.currentTarget.contains(e.relatedTarget))clearDropTargets()});
document.body.addEventListener('drop',e=>{if(!draggingId)return;const sourceHit=find(tasks,draggingId);if(!sourceHit)return;const targetCard=e.target.closest('.task-node');const target=targetCard&&find(tasks,targetCard.dataset.id);const source=sourceHit.node;if(target&&target.node.id!==source.id&&!contains(source,target.node.id)){e.preventDefault();sourceHit.nodes.splice(sourceHit.nodes.indexOf(source),1);target.node.children=target.node.children||[];target.node.children.push(source);target.node.done=false;syncParents();save();render()}else if(e.target.closest('#task-list')){e.preventDefault();if(sourceHit.nodes!==tasks){sourceHit.nodes.splice(sourceHit.nodes.indexOf(source),1);tasks.unshift(source);syncParents();save();render()}}clearDropTargets()});
})();
