const KEY='daily-streaks-tasks-v1'; const $=s=>document.querySelector(s); let tasks=load(), editing=null, addingTo=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(tasks))}
function id(){return crypto.randomUUID()}
function find(nodes,target,parent=null){for(const node of nodes){if(node.id===target)return{node,parent,nodes};const hit=find(node.children||[],target,node);if(hit)return hit}return null}
function descendants(node,value){node.done=value;(node.children||[]).forEach(child=>descendants(child,value))}
function syncParents(){function visit(node){const kids=node.children||[];kids.forEach(visit);if(kids.length)node.done=kids.every(k=>k.done)}tasks.forEach(visit)}
function openCount(nodes=tasks){return nodes.reduce((n,t)=>n+(t.done?0:1)+openCount(t.children||[]),0)}
function count(nodes){return nodes.reduce((n,t)=>n+1+count(t.children||[]),0)}
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function renderNode(t){const kids=t.children||[], childLabel=kids.length?`<span class="child-count">${count(kids)} subtask${count(kids)===1?'':'s'}</span>`:'';return `<div class="task-node" data-id="${t.id}"><div class="task-row ${t.done?'done':''}"><button class="check ${t.done?'done':''}" data-action="toggle" aria-label="Toggle ${esc(t.title)}"></button><span class="task-name">${esc(t.title)}</span>${childLabel}<div class="row-actions"><button class="action" data-action="add">+ Subtask</button><button class="action" data-action="edit">Edit</button><button class="action delete" data-action="delete">×</button></div></div>${kids.length?`<div class="children">${kids.map(renderNode).join('')}</div>`:''}</div>`}
function render(){syncParents();save();const open=tasks.filter(t=>!t.done), done=tasks.filter(t=>t.done);$('#open-summary').textContent=openCount()?`${openCount()} open task${openCount()===1?'':'s'}`:'Everything is complete.';$('#task-list').innerHTML=open.map(renderNode).join('');$('#empty-state').hidden=tasks.length>0;$('#completed-section').hidden=!done.length;$('#completed-count').textContent=done.length?`(${done.length})`:'';$('#completed-list').innerHTML=done.map(renderNode).join('')}
function openDialog({task=null,parent=null}={}){editing=task?.id||null;addingTo=parent?.id||null;const f=$('#task-form');f.reset();$('#dialog-kicker').textContent=task?'EDIT TASK':parent?'NEW SUBTASK':'NEW TASK';$('#dialog-title').textContent=task?'Rename this task':parent?`Break down “${parent.title}”`:'What needs doing?';$('#save-task').textContent=task?'Save changes':'Add task';if(task)f.title.value=task.title;$('#task-dialog').showModal();f.title.focus()}
function close(){document.querySelectorAll('dialog[open]').forEach(d=>d.close())}
$('#add-root').onclick=()=>openDialog();$('#add-empty').onclick=()=>openDialog();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);
document.body.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const hit=find(tasks,button.closest('.task-node').dataset.id);if(!hit)return;const action=button.dataset.action;if(action==='toggle'){descendants(hit.node,!hit.node.done);syncParents();save();render()}if(action==='add')openDialog({parent:hit.node});if(action==='edit')openDialog({task:hit.node});if(action==='delete'&&confirm(`Delete “${hit.node.title}” and all of its subtasks?`)){hit.nodes.splice(hit.nodes.indexOf(hit.node),1);syncParents();save();render()}});
$('#task-form').onsubmit=e=>{e.preventDefault();const title=e.currentTarget.title.value.trim();if(!title)return;if(editing)find(tasks,editing).node.title=title;else {const newTask={id:id(),title,done:false,children:[]};if(addingTo){const parent=find(tasks,addingTo).node;parent.children.push(newTask);parent.done=false}else tasks.unshift(newTask)}save();close();render()};
$('#toggle-completed').onclick=()=>{$('#completed-list').hidden=!$('#completed-list').hidden};render();
